version: '3.8'

networks:
  my_network:
    driver: bridge
    name: my_network


services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user_test
      POSTGRES_PASSWORD: password_test
      POSTGRES_DB: mydatabase_test

  auth:
    build: .
    volumes:
      - "./src:/app/src"
    ports:
      - "5432:5432"
      - "8001:8001"
    depends_on:
      - db

