apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-dep
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: friend-service
  template:
    metadata:
      labels:
        app: friend-service
    spec:
      containers:
      - name: friend-container
        image: friend-img:0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8001


---
apiVersion: v1
kind: Service
metadata:
  name: friend-service
spec:
  type: NodePort
  selector:
    app: friend-service
  ports:
    - port: 8001           # Port cible pour le conteneur
      targetPort: 8001      # Port exposé par le conteneur
      nodePort: 30002       # Port NodePort pour accéder au service
